import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc'
import isBetween from 'dayjs/plugin/isBetween'
import weekOfYear from 'dayjs/plugin/weekOfYear'
import relativeTime from 'dayjs/plugin/relativeTime'
import updateLocale from 'dayjs/plugin/updateLocale'

// --- Centralized Dayjs Configuration ---
dayjs.extend(utc)
dayjs.extend(isBetween)
dayjs.extend(weekOfYear)
dayjs.extend(relativeTime)
dayjs.extend(updateLocale)

// Optional: Update locale defaults if needed globally
dayjs.updateLocale('en', {
  relativeTime: {
    future: 'in %s',
    past: '%s ago',
    s: 'a few seconds',
    m: 'a minute',
    mm: '%d minutes',
    h: 'an hour',
    hh: '%d hours',
    d: 'a day',
    dd: '%d days',
    w: 'a week',
    ww: '%d weeks',
    M: 'a month',
    MM: '%d months',
    y: 'a year',
    yy: '%d years',
  },
  // Add week start day if needed, e.g., weekStart: 1 for Monday
})
// --- End Configuration ---

/**
 * Default time values that Plaid uses when institutions don't provide specific transaction times.
 * These are treated as "date-only" values and displayed without the time component.
 *
 * Based on observed behavior:
 * - Midnight (00:00:00 UTC): Most common default
 * - 4:00 AM UTC: Common default for some institutions
 * - 5:00 AM UTC: Common default for some institutions
 */
const PLAID_DEFAULT_TIMES = [
  { hour: 0, minute: 0, second: 0 }, // Midnight UTC
  { hour: 4, minute: 0, second: 0 }, // 4 AM UTC
  { hour: 5, minute: 0, second: 0 }, // 5 AM UTC
] as const

/**
 * Parses a date string as UTC.
 * Ensures consistent handling of timestamps from the database.
 * @param dateString ISO 8601 string or Date object
 * @returns Dayjs object in UTC mode
 */
export const parseDateUTC = (dateString: string | Date): dayjs.Dayjs => {
  return dayjs.utc(dateString)
}

/**
 * Formats a transaction date for display in the list.
 * Shows the date ('MMM D') if the time appears to be a default value (midnight or other common defaults).
 * Shows the time ('h:mm A UTC') otherwise to preserve and make explicit the original UTC transaction time.
 * @param dateString ISO 8601 string or Date object from DB
 * @returns Formatted string (e.g., "Apr 14" or "10:32 AM UTC")
 */
export const formatTransactionDisplayDate = (
  dateString: string | Date,
): string => {
  const txDateTimeUTC = parseDateUTC(dateString)

  // Check if this looks like a default time value from Plaid
  const hour = txDateTimeUTC.hour()
  const minute = txDateTimeUTC.minute()
  const second = txDateTimeUTC.second()

  const isDefaultTime = PLAID_DEFAULT_TIMES.some(
    defaultTime =>
      hour === defaultTime.hour &&
      minute === defaultTime.minute &&
      second === defaultTime.second,
  )

  if (isDefaultTime) {
    // Likely a default time value, show just the date
    return txDateTimeUTC.format('MMM D')
  } else {
    // Has a specific time - show it with UTC indicator to make timezone explicit
    return txDateTimeUTC.format('h:mm A') + ' UTC'
  }
}

/**
 * Formats the date part of a timestamp string in UTC.
 * @param dateString ISO 8601 string or Date object from DB
 * @returns Formatted date string (e.g., "April 15, 2025")
 */
export const formatDateUTC = (dateString: string | Date): string => {
  return dayjs.utc(dateString).format('MMMM D, YYYY') // Use UTC
}

/**
 * Formats the time part of a timestamp string in the user's local timezone.
 * @param dateString ISO 8601 string or Date object from DB
 * @returns Formatted time string (e.g., "5:00 PM")
 */
export const formatTimeLocal = (dateString: string | Date): string => {
  return dayjs(dateString).format('h:mm A')
}

/**
 * Determines the transaction group key based on its UTC date.
 * Always returns the month and year ('MMMM YYYY') for grouping.
 * @param dateString ISO 8601 string or Date object from DB
 * @returns Group key ('MMMM YYYY')
 */
export const getTransactionGroupKeyUTC = (
  dateString: string | Date,
): string => {
  const txDate = parseDateUTC(dateString) // Transaction date in UTC
  return txDate.format('MMMM YYYY') // Always group by Month YYYY
}

/**
 * Gets the display title and date range string for a transaction group header.
 * Since grouping is by month, title and date range are both the month/year string.
 *
 * @param groupKey The key generated by getTransactionGroupKeyUTC ('MMMM YYYY')
 * @returns Object with { title: string; date: string } where both are the month/year
 */
export const getTransactionGroupDisplayInfo = (
  groupKey: string,
): { title: string; date: string } => {
  const title = groupKey
  const dateRange = groupKey // Display the same month/year string

  return { title, date: dateRange }
}
