name: Format and Lint
on:
  pull_request_target:
    branches: [main, deploy]
  push:
    branches: [main]
jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Setup Wasp
        run: |
          curl -sSL https://get.wasp-lang.dev/installer.sh | sh
          wasp compile

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      - name: Lint and fix
        run: npm run lint:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: apply formatting and linting changes'
          branch: ${{ github.head_ref }}
          commit_options: '--no-verify'
